package it.disim.univaq.sose.healthsoa.anagrafe.endpoint;

import it.disim.univaq.sose.healthsoa.anagrafe.generated.AllergyList;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.AnagrafePortType;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.ConditionList;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetAllergiesRequest;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetAllergiesResponse;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetMedicalHistoryRequest;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetMedicalHistoryResponse;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetPatientByIdRequest;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.GetPatientByIdResponse;
import it.disim.univaq.sose.healthsoa.anagrafe.generated.Patient;
import it.disim.univaq.sose.healthsoa.anagrafe.service.AnagrafeService;
import jakarta.jws.WebService;

/**
 * SOAP endpoint implementation for the Anagrafe Pazienti service.
 *
 * <p>Implements the {@link AnagrafePortType} interface generated by CXF from
 * {@code anagrafe.wsdl}. This class is the sole entry point for all SOAP calls:
 * it delegates the actual business logic to {@link AnagrafeService} and wraps
 * the returned objects in the appropriate JAXB response wrappers.
 *
 * <p>Published at {@code /soap/anagrafe} by {@code AnagrafeServiceApplication.anagrafeEndpoint()}.
 * Clients can obtain the WSDL at {@code http://host:9101/soap/anagrafe?wsdl}.
 *
 * <p>Operations:
 * <ul>
 *   <li>{@link #getPatientById} - demographic lookup;</li>
 *   <li>{@link #getMedicalHistory} - ICD-10 coded condition list;</li>
 *   <li>{@link #getAllergies} - known allergy list.</li>
 * </ul>
 */
@WebService(
        serviceName   = "AnagrafeService",
        portName      = "AnagrafePort",
        targetNamespace = "http://anagrafe.healthsoa.sose.univaq.disim.it/",
        endpointInterface = "it.disim.univaq.sose.healthsoa.anagrafe.generated.AnagrafePortType",
        wsdlLocation  = "classpath:wsdl/anagrafe.wsdl"
)
public class AnagrafeEndpoint implements AnagrafePortType {

    private final AnagrafeService anagrafeService;

    public AnagrafeEndpoint(AnagrafeService anagrafeService) {
        this.anagrafeService = anagrafeService;
    }

    /**
     * Returns demographic data for the requested patient.
     *
     * @param parameters SOAP request carrying the numeric patient identifier
     * @return SOAP response wrapping the {@code Patient} JAXB type
     */
    @Override
    public GetPatientByIdResponse getPatientById(GetPatientByIdRequest parameters) {
        Patient patient = anagrafeService.getPatientById(parameters.getPatientId());
        GetPatientByIdResponse response = new GetPatientByIdResponse();
        response.setPatient(patient);
        return response;
    }

    /**
     * Returns the full ICD-10 coded medical history for the requested patient.
     *
     * @param parameters SOAP request carrying the numeric patient identifier
     * @return SOAP response wrapping the {@code ConditionList} JAXB type
     */
    @Override
    public GetMedicalHistoryResponse getMedicalHistory(GetMedicalHistoryRequest parameters) {
        ConditionList history = anagrafeService.getMedicalHistory(parameters.getPatientId());
        GetMedicalHistoryResponse response = new GetMedicalHistoryResponse();
        response.setMedicalHistory(history);
        return response;
    }

    /**
     * Returns all known allergies for the requested patient.
     *
     * @param parameters SOAP request carrying the numeric patient identifier
     * @return SOAP response wrapping the {@code AllergyList} JAXB type
     */
    @Override
    public GetAllergiesResponse getAllergies(GetAllergiesRequest parameters) {
        AllergyList allergies = anagrafeService.getAllergies(parameters.getPatientId());
        GetAllergiesResponse response = new GetAllergiesResponse();
        response.setAllergies(allergies);
        return response;
    }

}
