package it.disim.univaq.sose.healthsoa.coordinator.dto;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * A single clinical risk flag detected by the {@code RiskAnalyzer}.
 *
 * <p>Each flag describes one specific clinical concern. The {@code severity} field
 * determines its contribution to the overall {@code FitnessReport.outcome}:
 * one or more CRITICAL flags → {@code NON_IDONEO}; only WARNING flags →
 * {@code CON_RISERVA}; no flags → {@code IDONEO}.
 *
 * <p>Flags are generated by the rules in {@code RiskAnalyzer} (specification §6):
 * <ul>
 *   <li>Anomalous lab measurements ({@code anomalyFlag=true} on any measurement);</li>
 *   <li>Nephrotoxic prescriptions in a patient with impaired renal markers;</li>
 *   <li>Prescriptions containing a known allergen;</li>
 *   <li>Critical radiology findings ({@code criticalFlag=true} on an imaging report).</li>
 * </ul>
 */
@Schema(description = "A clinical risk flag detected during fitness assessment")
public class RiskFlag {

    /**
     * Flag category:
     * {@code CONTROINDICAZIONE_FARMACO} - drug contraindication;
     * {@code VALORE_CRITICO} - critical lab value;
     * {@code ALLERGIA_RILEVANTE} - allergy-prescription conflict;
     * {@code ALTRO} - other (e.g., critical imaging finding).
     */
    @Schema(description = "Risk category",
            allowableValues = {"CONTROINDICAZIONE_FARMACO", "VALORE_CRITICO", "ALLERGIA_RILEVANTE", "ALTRO"},
            example = "VALORE_CRITICO")
    private String type;      // CONTROINDICAZIONE_FARMACO, VALORE_CRITICO, ALLERGIA_RILEVANTE, ALTRO

    /** Human-readable explanation of the specific risk detected. */
    @Schema(description = "Human-readable description of the risk", example = "Creatinine above threshold: 2.5 mg/dL")
    private String description;

    /**
     * Severity level:
     * {@code INFO} - informational only, no action required;
     * {@code WARNING} - caution, conditional fitness;
     * {@code CRITICAL} - patient is not fit (NON_IDONEO).
     */
    @Schema(description = "Risk severity",
            allowableValues = {"INFO", "WARNING", "CRITICAL"}, example = "WARNING")
    private String severity;  // INFO, WARNING, CRITICAL

    /** Name of the service or data source that produced the flag. */
    @Schema(description = "Data source that generated this flag", example = "RiskAnalyzer/Laboratorio")
    private String source;

    public RiskFlag() {}

    public RiskFlag(String type, String description, String severity, String source) {
        this.type = type;
        this.description = description;
        this.severity = severity;
        this.source = source;
    }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }
    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }
}
